//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyuruDurum
    {
        public int ID { get; set; }
        public Nullable<int> DuyuruID { get; set; }
        public string DuyuruHareketi { get; set; }
        public Nullable<System.DateTime> HareketTarihi { get; set; }
    
        public virtual Duyurular Duyurular { get; set; }
    }
}
